"""Bob example: a note-taking app equivalent to payload/apps/template/.

Same behaviour as the hand-written template (a saved note, a status tick),
written with zero HTML or JavaScript -- proof Bob's output round-trips
correctly. Run `python3 tools/bob/bob.py` (or this file directly) to
regenerate payload/apps/bob-notes/{app.json,index.html}.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))         # tools/bob/examples
_BOB_DIR = os.path.dirname(_HERE)                           # tools/bob
_REPO_ROOT = os.path.dirname(os.path.dirname(_BOB_DIR))     # repo root

sys.path.insert(0, _BOB_DIR)
import bob  # noqa: E402

app = bob.App(
    id="bob-notes",
    name="Bob Notes",
    description="A simple saved note, built with Bob instead of hand-written HTML/JS",
    icon="BN",
    categories=["NETHOS", "Development"],
    permissions=["system", "storage"],
    width=760,
    height=560,
)

app.body(
    bob.header("Bob Notes", "generated by tools/bob — edit the .py, not the .html"),
    bob.card(
        "Persistent storage",
        bob.text(
            "Saved to ~/.local/state/nethos/apps/bob-notes.json, "
            "so it survives reboots, reinstalls and profile wipes.",
            dim=True,
        ),
        bob.label("Your note", for_="note"),
        bob.textarea("note", placeholder="Type something…"),
        bob.row(
            bob.button("Save", id="save", primary=True),
            bob.button("Clear", id="clear"),
            bob.spacer(),
            bob.status_line("saved-at", initial=""),
        ),
    ),
    bob.card(
        "System",
        bob.status_line("status"),
    ),
)

app.actions(
    bob.on_load(
        bob.SetValue("note", bob.StorageGet("note", "")),
    ),
    bob.on_click("save", [
        bob.StorageSet("note", bob.Val("note")),
        bob.StorageSet("savedAt", bob.Raw("Date.now()")),
        bob.SetText("saved-at", bob.Fmt("saved {t}", t=bob.Now())),
        bob.Toast("Saved", "good"),
    ]),
    bob.on_click("clear", [
        bob.StorageSet("note", bob.Lit("")),
        bob.SetValue("note", bob.Lit("")),
        bob.SetText("saved-at", bob.Lit("")),
        bob.Toast("Cleared"),
    ]),
    bob.every(
        5000,
        bob.Let("s", bob.SystemStatus()),
        bob.SetText(
            "status",
            bob.Fmt(
                "{user}@{host} · load {load} · mem {mem}% · up {up}s",
                user=bob.Prop(bob.Var("s"), "user"),
                host=bob.Prop(bob.Var("s"), "host"),
                load=bob.Prop(bob.Var("s"), "load"),
                mem=bob.Prop(bob.Prop(bob.Var("s"), "mem"), "used_pct"),
                up=bob.Prop(bob.Var("s"), "uptime"),
            ),
        ),
    ),
)

# Builds both when run directly and when imported (tools/bob/bob.py imports
# every examples/*.py to regenerate all of them at once).
app.build(os.path.join(_REPO_ROOT, "payload", "apps", "bob-notes"))
